DERMNET_DISEASE_NAME = ['Acne and Rosacea Photos',
                        'Actinic Keratosis Basal Cell Carcinoma and other Malignant Lesions',
                        'Atopic Dermatitis Photos',
                        'Bullous Disease Photos',
                        'Cellulitis Impetigo and other Bacterial Infections',
                        'Eczema Photos',
                        'Exanthems and Drug Eruptions',
                        'Hair Loss Photos Alopecia and other Hair Diseases',
                        'Herpes HPV and other STDs Photos',
                        'Light Diseases and Disorders of Pigmentation',
                        'Lupus and other Connective Tissue diseases',
                        'Melanoma Skin Cancer Nevi and Moles',
                        'Nail Fungus and other Nail Disease',
                        'Poison Ivy Photos and other Contact Dermatitis',
                        'Psoriasis pictures Lichen Planus and related diseases',
                        'Scabies Lyme Disease and other Infestations and Bites',
                        'Seborrheic Keratoses and other Benign Tumors',
                        'Systemic Disease',
                        'Tinea Ringworm Candidiasis and other Fungal Infections',
                        'Urticaria Hives',
                        'Vascular Tumors',
                        'Vasculitis Photos',
                        'Warts Molluscum and other Viral Infections',
                        'Other Disease']
Fitzpatrick17k_DISEASE_NAME = ['acanthosis nigricans',
 'acne',
 'acne vulgaris',
 'acquired autoimmune bullous diseaseherpes gestationis',
 'acrodermatitis enteropathica',
 'actinic keratosis',
 'allergic contact dermatitis',
 'aplasia cutis',
 'basal cell carcinoma',
 'basal cell carcinoma morpheiform',
 'becker nevus',
 'behcets disease',
 'calcinosis cutis',
 'cheilitis',
 'congenital nevus',
 'dariers disease',
 'dermatofibroma',
 'dermatomyositis',
 'disseminated actinic porokeratosis',
 'drug eruption',
 'drug induced pigmentary changes',
 'dyshidrotic eczema',
 'eczema',
 'ehlers danlos syndrome',
 'epidermal nevus',
 'epidermolysis bullosa',
 'erythema annulare centrifigum',
 'erythema elevatum diutinum',
 'erythema multiforme',
 'erythema nodosum',
 'factitial dermatitis',
 'fixed eruptions',
 'folliculitis',
 'fordyce spots',
 'granuloma annulare',
 'granuloma pyogenic',
 'hailey hailey disease',
 'halo nevus',
 'hidradenitis',
 'ichthyosis vulgaris',
 'incontinentia pigmenti',
 'juvenile xanthogranuloma',
 'kaposi sarcoma',
 'keloid',
 'keratosis pilaris',
 'langerhans cell histiocytosis',
 'lentigo maligna',
 'lichen amyloidosis',
 'lichen planus',
 'lichen simplex',
 'livedo reticularis',
 'lupus erythematosus',
 'lupus subacute',
 'lyme disease',
 'lymphangioma',
 'malignant melanoma',
 'melanoma',
 'milia',
 'mucinosis',
 'mucous cyst',
 'mycosis fungoides',
 'myiasis',
 'naevus comedonicus',
 'necrobiosis lipoidica',
 'nematode infection',
 'neurodermatitis',
 'neurofibromatosis',
 'neurotic excoriations',
 'neutrophilic dermatoses',
 'nevocytic nevus',
 'nevus sebaceous of jadassohn',
 'papilomatosis confluentes and reticulate',
 'paronychia',
 'pediculosis lids',
 'perioral dermatitis',
 'photodermatoses',
 'pilar cyst',
 'pilomatricoma',
 'pityriasis lichenoides chronica',
 'pityriasis rosea',
 'pityriasis rubra pilaris',
 'porokeratosis actinic',
 'porokeratosis of mibelli',
 'porphyria',
 'port wine stain',
 'prurigo nodularis',
 'psoriasis',
 'pustular psoriasis',
 'pyogenic granuloma',
 'rhinophyma',
 'rosacea',
 'sarcoidosis',
 'scabies',
 'scleroderma',
 'scleromyxedema',
 'seborrheic dermatitis',
 'seborrheic keratosis',
 'solid cystic basal cell carcinoma',
 'squamous cell carcinoma',
 'stasis edema',
 'stevens johnson syndrome',
 'striae',
 'sun damaged skin',
 'superficial spreading melanoma ssm',
 'syringoma',
 'telangiectases',
 'tick bite',
 'tuberous sclerosis',
 'tungiasis',
 'urticaria',
 'urticaria pigmentosa',
 'vitiligo',
 'xanthomas',
 'xeroderma pigmentosum']
HAM10000_DISEASE_NAME = ["akiec", "bcc", "bkl", "df", "mel", "nv", "vasc"]
HAM10000_DISEASE_MAPPING_NAME = {"akiec": "Actinic keratoses and intraepithelial carcinoma / Bowen's disease",
                                 "bcc": "basal cell carcinoma",
                                 "bkl": "benign keratosis-like lesions (solar lentigines / seborrheic keratoses and lichen-planus like keratoses)",
                                 "df": "dermatofibroma", "mel": "melanoma", "nv": "melanocytic nevi ",
                                 "vasc": "vascular lesions (angiomas, angiokeratomas, pyogenic granulomas and hemorrhage)"}
HAM10000_DISEASE_NAME_FULL = ["Actinic keratoses and intraepithelial carcinoma / Bowen's disease", "basal cell carcinoma","benign keratosis-like lesions (solar lentigines / seborrheic keratoses and lichen-planus like keratoses)",
                              "dermatofibroma", "melanoma", "melanocytic nevi ", "vascular lesions (angiomas, angiokeratomas, pyogenic granulomas and hemorrhage)"]
SYNONYM_DICT_HAM10000 = {
    "akiec": {"akiec", "actinic", "keratosis", "actinic keratosis" "intraepithelial", "bowen", "bowen's", "ak",
              "solar keratosis"},
    "bcc": {"bcc", "basal", "cell", "carcinoma", "basalioma"},
    "bkl": {"bkl", "benign keratosis", "solar lentigines", "seborrheic keratosis", "lichen planus-like",
            "solar lentigo"},
    "df": {"df", "dermatofibroma"},
    "mel": {"mel", "melanoma", "malignant melanoma"},
    "nv": {"nv", "nevus", "nevi", "melanocytic nevus", "mole", "moles"},
    "vasc": {"vasc", "vascular", "angioma", "angiomas", "angiokeratoma", "pyogenic granuloma", "hemorrhage",
             "blood vessel"}
}
SYNONYM_DICT_DERMNET = {
    'acne and rosacea photos': {'rosacea acne', 'sebDerem', 'rosacea steroid', 'Forest', 'acne pustular',
                                'hidradenitis suppurativa', 'fordyce spots', 'acne scar', 'Sebaceous glands Areola',
                                'SteroidPerioral', 'RosaceaFulFAce', 'nevus comedonicus', 'Perioral Derm Eye',
                                'RosaceaOK', 'rosacea', 'VascularFace', 'rhnophymas', 'hyperhidrosis', 'acne',
                                'Rhinophyma', 'rhinophyma', 'ComedonesEars', 'acne histology', 'rosacea nose',
                                'Hidradenitis Suppurativa Areola', 'PerioralDerm', 'acne rosacea', 'RosaceaMilia',
                                'acne closed comedo', 'sebaceous glands upper lip', 'milia', 'acne primary lesion',
                                'perioral dermatitis', 'acne cystic', 'acne open comedo', 'acne infantile',
                                'acne excoriated', 'minocycline pigmentation'},
    'actinic keratosis basal cell carcinoma and other malignant lesions': {'squamous cell carcinoma hand arm',
                                                                           'extramammary paget disease', 'leukoplakia',
                                                                           'actinic cheilitis sq cell lip',
                                                                           'basal cell carcinoma nose',
                                                                           'actinic keratosis arm',
                                                                           'epidermodysplasia verruciformis',
                                                                           'merkel cell cancer', 'dermatofibrosarcoma',
                                                                           'actinic keratosis lesion',
                                                                           'basal cell carcinoma superficial',
                                                                           'basal cell carcinoma ear',
                                                                           'squamous cell carcinoma ear',
                                                                           'basal cell carcinoma sclerosing',
                                                                           'arsenical keratoses',
                                                                           'basal cell carcinoma trunk ext', 'ak',
                                                                           'squamous cell carcinoma nose',
                                                                           'actinic keratosis nose', 'keratosis',
                                                                           'squamous cell carcinoma scalp',
                                                                           'basal cell carcinoma lesion',
                                                                           'actinic keratosis',
                                                                           'actinic keratosis horn',
                                                                           'granulation tissue', 'bowens disease',
                                                                           'actinic keratosis pigmented',
                                                                           'squamous cell carcinoma lesion',
                                                                           'actinic keratosis face',
                                                                           'actinic keratosis hand', 'ctcl',
                                                                           'malignant lesion', 'leukemia',
                                                                           'basal cell nevus syndrome',
                                                                           'paget disease breast',
                                                                           'actinic keratosis ear', "bowen's",
                                                                           'verrucous carcinoma',
                                                                           'basal cell carcinoma aldara',
                                                                           'squamous cell carcinoma vulva', 'bowen',
                                                                           'squamous cell carcinoma leg',
                                                                           'cutaneous horn',
                                                                           'squamous cell carcinoma lip',
                                                                           'basal cell carcinoma lid',
                                                                           'basal cell carcinoma pigmented',
                                                                           'metastasis', 'basal cell carcinoma lip',
                                                                           'basal cell carcinoma histology',
                                                                           'squamous cell carcinoma face',
                                                                           'basal cell carcinoma face', 'actinic',
                                                                           'basal cell carcinoma scalp',
                                                                           'basal cell carcinoma', 'bcc',
                                                                           'actinic keratosis FU',
                                                                           'basal cell carcinoma arm'},
    'atopic dermatitis photos': {'IMG', 'PityriasisAlba', 'atopicChild', 'EczemaAreolae', 'KeratosisIMG GP',
                                 'DermatitisAreola', 'diaperDerm', 'hyperLinearCrease', 'Ichthyosis', 'Atopic',
                                 'IchthyosisSexLinked', 'KeratosisPilaris', 'hyperkeratosis', 'atopicDermok',
                                 'DermatitisLids', 'kerPilarisFlorid', 'keratosisPilaris', 'icthyosis',
                                 'IchthosisIMG GP', 'AtopicFacek', 'SexLinkedEchthyosis', 'ichthyosis', 'atopicFoot',
                                 '.DS Store', 'atopicAdult', 'child', 'atopicFeet', 'atopic dermatitis', 'atopic',
                                 'icththyosis', 'AtopicMouth', 'AtopicLichenification', 'atopicFace', 'DryFeet',
                                 'AtopicFossaq', 'AtopicChild', 'AtopicIMG GP', 'atopicFlid', 'AtopicFaceok',
                                 'AtopicFace', 'xlinkedIcthyosis', 'thIMG', 'AtopicDerm', 'eczema', 'SexLinkIchthosis'},
    'bullous disease photos': {'localized pemphigoid', 'bullous pemphigoid', 'chronic bullous dermatosis childhood',
                               'dermatitis herpetiformis', 'dariers disease', 'pemphigus foliaceous', 'pemphigus',
                               'diabetic bullae', 'bullous disease', 'pemphigoid', 'herpes gestationis',
                               'grovers disease', 'benign familial chronic pemphigus', 'epidermolysis bullosa'},
    'cellulitis impetigo and other bacterial infections': {'bacterial infection', 'Erysipelas',
                                                           'Streptococci Anal Penis', 'Cellulitis', 'Sycosis Barbae',
                                                           'pitted keratolysis', 'HotTubIMG GP',
                                                           'Staphylococcal Folliculitis', 'Furuncles Carbuncles',
                                                           'Balanitis Bacterial', 'Pseudomonfoll', 'Erysipeloid',
                                                           'otitis externa', 'atypical mycobacterium', 'Leprosy',
                                                           'Pseudomonas Folliculitis', 'meningococcemia', 'EczemaStaph',
                                                           'Ecthyma', 'Folliculitis', 'Botryomycosis Staph', 'impetigo',
                                                           'cellulitis', 'Pseudomonas Cellulitis'},
    'eczema photos': {'stasis dermatitis', 'DermatitisLeg', 'eczema axillae', 'eczema chronic', 'eczema hand',
                      'maceration', 'eczema subacute', 'DermatitisArm', 'eczema trunk generalized', 'eczema face',
                      'milroy disease', 'hyperkeratosis', 'DermatitisLids', 'eczema arms', 'eczema ears',
                      'desquamation', 'fissure', 'dermatitisDrug', 'dermatitis', 'eczema lids', 'pompholyx',
                      'parasitosis psychogenic', 'eczema impetiginized', 'eczema nummular', 'factitial dermatitis',
                      'eczema vulva', 'heels dry cracked', 'fiberglass dermatitis', 'phlebitis superficial',
                      'chapped fissured feet', 'eczema areola', 'eczema leg', 'Dyshidrosis', 'lichen simplex chronicus',
                      'eczema fingertips', 'keratolysis exfoliativa', 'eczema foot', 'eczema asteatotic',
                      'neurotic excoriations', 'eczema', 'prurigo nodularis', 'iododerma', 'eczema acute',
                      'id reaction'},
    'exanthems and drug eruptions': {'drug eruptions', 'gianotti crosti', 'viral exanthems', 'hand foot mouth disease',
                                     'cytomegalovirus', 'scarlet fever', 'PostInfDesquam', 'kawasaki syndrome',
                                     'exfoliative dermatitis', 'desquamationViral GP', 'drug reaction', 'exanthem',
                                     'fixed drug eruption', 'roseola infantum', 'enterovirus',
                                     'minocycline pigmentation', 'drug eruption', 'erythema infectiosum'},
    'hair loss photos alopecia and other hair diseases': {'hirsutism', 'alopecia', 'acne keloidalis',
                                                          'trichorrhexis nodosa', 'pseudopelade',
                                                          'androgenic alopecia women', 'trichotillomania',
                                                          'androgenic alopecia men', 'alopecia areata',
                                                          'telogen effluvium', 'pili torti', 'dissecting cellulitis',
                                                          'baldness', 'discoid lupus', 'tufted folliculitis',
                                                          'hair loss', 'lichen planopilaris', 'hot comb alopecia',
                                                          'folliculitis decalvans'},
    'herpes hpv and other stds photos': {'AIDS', 'warts mouth', 'herpes type  primary', 'herpesAnal', 'warts genital',
                                         'herpes type  recurrent', 'std', 'bacterial vaginosis', 'chancroid',
                                         'sexually transmitted disease', 'herpes', 'gonorrhea', 'pearly penile papules',
                                         'molluscum contagiosum', 'syphilis', 'genital herpes simplex', 'genital warts',
                                         'hpv', 'genital ulcers'},
    'light diseases and disorders of pigmentation': {'hydroa aestivale', 'nevus anemicus',
                                                     'erythema dyschromium perstans', 'colloid milia',
                                                     'phototoxic reactions doxycycline', 'sun damaged skin',
                                                     'light disease', 'erythema ab igne', 'pigmentation disorder',
                                                     'vitiligo', 'albinism', 'mongolian spot', 'melasma',
                                                     'polymorphous light eruption', 'weathering nodules',
                                                     'actinic comedones', 'idiopathic guttate hypomelanosis', 'milia',
                                                     'post inflammatory hyperpigmentation', 'poikiloderma civatte',
                                                     'phototoxic reactions', 'lentigo adults', 'porphyrias',
                                                     'pseudo porphyria', 'piebaldism'},
    'lupus and other connective tissue diseases': {'lupus subacute', 'scleroderma', 'lupus acute',
                                                   'mixed connective tissue disease', 'systemic lupus erythematosus',
                                                   'erythromelalgia', 'dermatomyositis', 'lupus chronic cutaneous',
                                                   'mucinosis', 'sle', 'connective tissue disease', 'acrocyanosis',
                                                   'crest syndrome', 'raynaud disease', 'lupus', 'rheumatoid nodule',
                                                   'chilblains perniosis', 'morphea'},
    'melanoma skin cancer nevi and moles': {'halo nevus', 'nevus repigmented', 'blue nevus', 'nevus',
                                            'melanotic macule', 'nevus spilus', 'melanocytic nevus', 'blue nevus ota',
                                            'congenital nevus', 'atypical nevi dermoscopy', 'melanocytic nevi',
                                            'malignant melanoma', 'lentigo maligna', 'skin cancer', 'melanoma',
                                            'becker nevus', 'atypical nevi', 'atypical nevi trunk', 'mole',
                                            'mongolian spot'},
    'nail fungus and other nail disease': {'psoriasis', 'ingrown nail', 'koilonychia', 'acute paronychia',
                                           'congenital anomalies', 'splinter hemorrhage', 'yellow nails', 'onycholysis',
                                           'onychogryphosis', 'nail fungus', 'nail melanoma', 'normal variations',
                                           'mucous cyst', 'biting excoriation', 'ridging beading', 'trauma',
                                           'beaus lines', 'exostosis', 'fissure', 'proximal subungual onychomycosis',
                                           'onychomycosis', 'nail distal splitting', 'pincer nails',
                                           'chronic paronychia', 'alopecia areata', 'habit tic deformity',
                                           'periungual fibroma', 'pigmented bands', 'Bed Ridges',
                                           'pachyonychia congenita', 'white superficial onychomycosis', 'leukonychia',
                                           'lichen planus', 'BedRidges', 'periungual warts', 'terry nails', 'clubbing',
                                           'twenty nail dystrophy', 'distal subungual onychomycosis', 'eczema nail',
                                           'pseudomonas', 'median nail dystrophy', 'nail disease',
                                           'subungual hematoma'},
    'poison ivy photos and other contact dermatitis': {'allergic contact dermatitis', 'rhus dermatitis',
                                                       'cosmetic fragrance allergy', 'contact dermatitis',
                                                       'patch testing', 'metal dermatitis', 'poison ivy',
                                                       'angry back patch testing', 'allergic reaction', 'shoe allergy',
                                                       'systemically induced allergic dermatitis',
                                                       'irritant contact dermatitis'},
    'psoriasis pictures lichen planus and related diseases': {'psoriasisAnus', 'psoriasis', 'sebKerm',
                                                              'psoriasis digits', 'psoriasis palms soles',
                                                              'SebDermChest', 'Pityriasis Lichenoides',
                                                              'psoriatic arthritis', 'reiter syndrome',
                                                              'Lichen Sclerosis Vulva', 'SebDermPresternal',
                                                              'Psoriasis inversus', 'SebDermLids',
                                                              'Lichen Sclerosus Skin', 'Lichen Planus Hypertrophic',
                                                              'Psoriasis', 'sebdermFace', 'PsoriasisAnalPink',
                                                              'Lichen Nitidus', 'PsoriasisPinking', 'SebDermPrestern',
                                                              'Psoriasis sunburn', 'Lichen Sclerosus Penis',
                                                              'glutealPinking', 'lichen planus vaginal',
                                                              'Lichen Planus Drug', 'Lichen Planus Palm Soles',
                                                              'Psoriasis nails', 'Psoriasis Cellulitis',
                                                              'Lichen Planus Penis', 'psoriasis scalp',
                                                              'seborrheic dermatitis', 'Lichen Planus Oral',
                                                              'Psoriasis Hand', 'Axillary Granular Parakeratosis',
                                                              'pityriasis rosea', 'psoriasis erythrodermic',
                                                              'Psoriasis Chronic Plaque', 'Psoriasis Anus',
                                                              'psoriasis Chronic plaque', 'Psoriasis penis',
                                                              'Psoriasis Interferon Injection', 'lichen planus',
                                                              'psoriasis pustular generalized', 'OilSpotPsoriasis',
                                                              'tineaAmiantacea', 'pityriasis rubra pilaris',
                                                              'Psoriasis Guttate', 'Psoriasis Histology'},
    'scabies lyme disease and other infestations and bites': {'biting insects', 'rocky mountain spotted fever',
                                                              'cutaneous Larva Migrans', 'pubic lice',
                                                              'Coral Poisoning', 'caterpillar dermatitis',
                                                              'leishmaniasis', 'lyme disease', 'tick bite', 'duck itch',
                                                              'pediculosis body', 'dermatitis swimming',
                                                              'cactus granuloma', 'maculae cerulea',
                                                              'chigger Bites Bullous', 'BoxMiscIMG GP',
                                                              'Sea bathers eruption', 'scabies', 'jelly fish sting',
                                                              'cat bite', 'infestation', 'spider bite', 'myiasis',
                                                              'pediculosis lids', 'fire ants', 'flea bites'},
    'seborrheic keratoses and other benign tumors': {'seborrheic keratosis', 'hydrocystoma', 'accessory trachus',
                                                     'epidermal cyst', 'accessory nipple', 'follicular keratosis',
                                                     'dermatofibroma', 'syringoma', 'fibroma', 'collagenoma',
                                                     'seborrheic keratoses ruff', 'keratosis punctata',
                                                     'pseudo cyst auricle', 'dermatosis papulosa nigra',
                                                     'kyrle disease', 'chondrodermatitis nodularis', 'benign tumor',
                                                     'seborrheic keratoses smooth', 'acquired digital fibrokeratoma',
                                                     'pinkus tumor', 'neurofibromas', 'sebaceous hyperplasia',
                                                     'epidermal nevus', 'EpidermCystRuptured', 'skin tags polyps',
                                                     'stucco keratoses', 'melanoma mimic', 'cylindroma', 'skin tag',
                                                     'porokeratosis', 'trichofolliculoma', 'pilar cyst', 'keloids',
                                                     'seborrheicKeratosisCrop', 'Keratoacanthoma', 'keratoacanthoma',
                                                     'leiomyomata', 'seborrheic keratosis irritated',
                                                     'nevus sebaceous'},
    'systemic disease': {'necrobiosis lipoidica', 'lichen myxedematosus', 'amyloidosis', 'systemic disease', 'pellagra',
                         'pseudoxanthoma elasticum', 'granuloma annulare', 'degos disease', 'lipoid proteinosis',
                         'glucagonoma', 'sarcoid', 'rheumatoid nodule', 'pretibial myxedema', 'myxedema',
                         'internal disease', 'sebaceous adenoma', 'xanthomas', 'acanthosis nigricans',
                         'acrodermatitis enteropathica', 'elastosis perferans', 'nevoxanthoendothelioma',
                         'neurofibromatosis', 'tuberous sclerosis', 'Fibrofolliculoma', 'osler node',
                         'diabetes mellitus', 'lichen amyloidosis', 'cowden disease'},
    'tinea ringworm candidiasis and other fungal infections': {'kerion', 'actinomycosis', 'candidiasis vaginal',
                                                               'tinea', 'pitted keratolysis', 'candida groin',
                                                               'candida penis', 'confluent reticulate papillomatosis',
                                                               'candidaTongue', 'tinea hand dorsum', 'perleche',
                                                               'tinea body', 'tinea versicolor', 'tinea laboratory',
                                                               'tinea scalp', 'tinea incognito', 'TineaIncognito',
                                                               'tinea face', 'tinea beard', 'tinea groin',
                                                               'tinea primary lesion', 'tinea palm', 'CandidaAxillae',
                                                               'candidaIntertrigo', 'erythrasma', 'majocchi granuloma',
                                                               'north american blastomycosis', 'candidiasis Penis',
                                                               'candidiasis', 'candidiasis mouth', 'Candida',
                                                               'cheilitis', 'pityrosporum folliculitis',
                                                               'candidiasis diaper', 'ringworm', 'fungal infection',
                                                               'coccidiomycosis', 'tinea foot webs',
                                                               'tinea foot plantar', 'candidiasis large skin folds',
                                                               'tinea foot dorsum', 'intertrigo', 'id reaction',
                                                               'erosio interdigitalis blastomycetica'},
    'urticaria hives': {'dermagraphism', 'angioedema', 'hives Urticaria Acute', 'urticaria', 'Urticaria Vasculitis',
                        'cholinergic uriticaria', 'cold urticaria', 'PUPPP', 'hives', 'erythema annulare centrifugum',
                        'wheal', 'pressure urticaria'},
    'vascular tumors': {'thrombosed vein', 'cherry angioma', 'angioma', 'hemangioma infancy', 'Hemangioma Dermoscopy',
                        'angiokeratomas', 'venous lake', 'lymphangioma circumscriptum', 'vascular anomaly',
                        'unilateral telangiectasia', 'pyogenic granuloma', 'hemangioma', 'kaposi sarcoma',
                        'telangiectasias', 'vascular tumor', 'venous malformations', 'purpura vomiting',
                        'spider angioma'},
    'vasculitis photos': {'vasculitis', 'schamberg disease', 'pyoderma gangrenosum', 'livido reticularis',
                          'sweets syndrome', 'atrophy blanche', 'blood vessel', 'stevens johnson syndrome',
                          'granuloma faciale', 'erythema elevatum diutinum', 'henoch schonlein purpura',
                          'erythema multiforme', 'interstitial granulomatous dermatitis', 'erythema nodosum',
                          'inflammation'},
    'warts molluscum and other viral infections': {'warts plantar', 'herpes type  recurrent', 'ChickenPoxBack',
                                                   'herpes zoster', 'small pox', 'hand foot mouth', 'black heel',
                                                   'eczema herpeticum', 'molluscum contagiosum', 'warts oral',
                                                   'warts periungual', 'warts immunocompromised', 'herpes simplex',
                                                   'herpes Buttock', 'herpes type  primary', 'Herpes Hand',
                                                   'warts treatment', 'herpes mouth', 'warts flat', 'PeriungualWart',
                                                   'warts', 'herpes buttocks', 'herpes cutaneous', 'viral infection',
                                                   'warts cryotherapy', 'varicella', 'molluscum', 'wartmouth',
                                                   'wartMouth', 'warts common', 'eczema vaccinatum', 'wartCommon',
                                                   'corns', 'warts digitate'}}

ISIC_DISEASE_NAME = [
    'Malignant',
    'Benign'
]
ISIC_PRECSV_PATH = './PanDerm_ISIC_predprob.csv'

MEDGAMMA_EVALUATION_PATH = '/Volumes/T7/SkinGPT-X-EvaluationResults/Experiments/Diagnosis/Medgamma/filename_to_medgamma_pred.csv'
REASONINGLAYER_EVALUATION_PATH = '/Volumes/T7/SkinGPT-X-EvaluationResults/Experiments/Diagnosis/DermNet/SkinGPTX/Reasoning_output.csv'
CASEREVIEW_EVALUATION_PATH = '/Volumes/T7/SkinGPT-X-EvaluationResults/Experiments/Diagnosis/DermNet/SkinGPTX/CaseReview_output.csv'
MEDGAMMA_LABELS_PATH = '/Volumes/T7/SkinGPT-X-EvaluationResults/Experiments/Diagnosis/filename_to_label.csv'
REASONING_LABELS_PATH = '/Volumes/T7/SkinGPT-X-EvaluationResults/Experiments/Diagnosis/DermNet/SkinGPTX/filename_to_labels_Reasoning.csv'
CASEREVIEW_LABELS_PATH = '/Volumes/T7/SkinGPT-X-EvaluationResults/Experiments/Diagnosis/DermNet/SkinGPTX/filename_to_labels_CaseReview.csv'
BASE_IMAGE_DIRECTORY = '/Volumes/T7/SkinGPT-X-Dataset/Dermnet/test'

MEDGAMMA_WORDHIT_OUTPUT = '/Volumes/T7/SkinGPT-X-EvaluationResults/Experiments/Diagnosis/SkinGPTX/MEDGAMMA_word_hit.csv'
CASEREVIEW_WORDHIT_OUTPUT = '/Volumes/T7/SkinGPT-X-EvaluationResults/Experiments/Diagnosis/DermNet/SkinGPTX/CaseReview_word_hit.csv'
REASONING_WORDHIT_OUTPUT = '/Volumes/T7/SkinGPT-X-EvaluationResults/Experiments/Diagnosis/DermNet/SkinGPTX/REASONING_word_hit.csv'

DERMNET_DATASET_ROOT = '/Volumes/T7/SkinGPT-X-Dataset/Dermnet/test'
ISIC_DATASET_ROOT = '/Volumes/T7/SkinGPT-X-Dataset/ISIC_2024_Resize224/test'
ISIC_EVALUATION_ROOT = '/Volumes/T7/SkinGPT-X-EvaluationResults/ISIC/test'

DERMNET_EVALUATION_ROOT = '/Volumes/T7/SkinGPT-X-EvaluationResults/Dermnet/test'

SYNONYM_DICT = {
    "vascular": {"vasculitis", "vascular", "vasculitic"},
    "carcinoma": {"carcinoma"},
    "acne": {"acne", "acneiform", "actinic cheilitis"},
    "rosacea": {"rosacea", "rosaceous"},
    "candidiasis": {"candidiasis", "candidal"},
    "icththyosis": {"ichthyosis", "icththyosis"},
    "icthyosis": {"icthyosis", "ichthyosis", "icththyosis"},
    "kerpilarisflorid": {"keratosis", "kerpilarisflorid"},
    "dermatitis": {"dermatitis", "dermatomyositis", "dermatosis"},
    "pemphigoid": {"pemphigoid", "pemphigus"},
    "palm": {"palms", "palm"},
    "urticaria": {"urticaria", "urticarial"},
    "lesions": {"lesions", "lesion"},
    "heels": {"heels", "heel"},
    "eruptions": {"eruptions", "eruption"},
    "infections": {"infection", "infections"},
    "comedo": {"comedones"},
    "actinic": {"ak", "actinic"},
    "tumors": {"angiokeratomas", "tumors", "angiosarcoma", "angioma", "angiomas", "angiokeratoma", "melanoma"},
    "steroidperioral": {"steroidperioral", "perioral"},
    "exanthems": {"exanthems", "exabrgens", "rubra", "cutaneous", "larva", "migrans", "multiforme", "erythematosus",
                  "exanthem", "zoster", "miliaria", "infectiosum", "syphilis"},
    "eczema": {"eczematous", "eczema"}
}

EVALUATION_ROOT = '/225040511/project/Evaluation_Results/Dermnet/SkinGPT-X/'
EVALUATION_ROOT_fitzpatrick17k = '/225040511/project/Evaluation_Results/fitzpatrick17k/'
RDD_DISEASE_NAME = ['Behcet_Disease', 'Blue_Rubber_Bleb_Nevus_Syndrome', 'Cryopyridine-associated_periodic_syndrome', 'Cutaneous_neuroendocrine_Carcinoma', 'Dermatofibrosarcoma_Protuberans_Images', 'Epithelioid_Sarcoma', 'Generalized_Pustular_Psoriasis', 'Gorlin_Syndrome']
SUPERDEMNET_DISEASE_NAME = ['acanthosis nigricans', 'acne cystic', 'acne excoriated', 'acne histology', 'acne infantile', 'acne keloidalis', 'acne open comedo', 'acne primary lesion', 'acne scar', 'actinic cheilitis sq cell lip', 'actinomycosis', 'acute paronychia', 'aids', 'allergic contact dermatitis', 'alopecia areata', 'anagen effluvium', 'anal comedones', 'androgenic alopecia men', 'angioedema', 'arsenical keratoses', 'atopic', 'atypical mycobacterium', 'atypical nevi', 'av malformation', 'basal cell carcinoma arm', 'benign familial chronic pemphigus', 'biting excoriation', 'biting insects', 'black heel', 'blue nevus', 'boxmiscimg gp', 'bullous pemphigoid', 'candida', 'candidiasis large skin folds', 'candidiasis mouth', 'cellulitis', 'chapped fissured feet', 'cherry angioma', 'chilblains perniosis', 'chondrodermatitis nodularis', 'clubbing', 'cold urticaria', 'congenital nevus', 'corns', 'crest syndrome', 'ctcl', 'cutaneous horn', 'cutaneous larva migrans', 'cylindroma', 'degos disease', 'dermagraphism', 'dermatitis swimming', 'dermatitisarm', 'diabetes mellitus', 'diabetic bullae', 'dissecting cellulitis', 'distal subungual onychomycosis', 'drug eruption photosensitivity', 'drug eruptions', 'dry nails', 'duck itch', 'dyshidrosis', 'ecthyma gangrenosum', 'eczema', 'eczema areola', 'eczema fingertips', 'eczema herpeticum', 'eczema nummular', 'eczema subacute', 'eczema trunk generalized', 'enterovirus', 'epidermolysis bullosa', 'erosio interdigitalis blastomycetica', 'erysipelas', 'erythema ab igne', 'erythema annulare centrifugum', 'erythema multiforme', 'erythema nodosum', 'erythrasma', 'fibroma', 'folliculitis decalvans', 'furuncles carbuncles', 'gianotti crosti', 'granulation tissue', 'granuloma hair', 'habit tic deformity', 'halo nevus', 'hand foot mouth', 'hang nail', 'hemangioma infancy', 'henoch schonlein purpura', 'herpes gestationis', 'herpes mouth', 'herpes simplex', 'herpes type primary', 'herpes zoster', 'hidradenitis suppurativa', 'hyperkeratosis', 'ichthosis', 'idiopathic guttate hypomelanosis', 'impetigo', 'interstitial granulomatous dermatitis', 'intertrigo', 'kawasaki syndrome', 'keloids', 'keratoacanthoma', 'keratolysis exfoliativa', 'keratosispilaris', 'kerion', 'koilonychia', 'lentigo adults', 'leprosy', 'leukoplakia', 'lichen planus', 'lichen planus drug', 'lichen sclerosus skin', 'lichen simplex chronicus', 'lupus acute', 'lupus chronic cutaneous', 'lyme disease', 'lymphangioma circumscriptum', 'lymphosarcoma', 'median nail dystrophy', 'melanocytic nevi', 'melanoma mimic', 'melasma', 'metal dermatitis', 'metastasis', 'milia', 'molluscum contagiosum', 'morphea', 'mucous cyst', 'myiasis', 'nail distal splitting', 'nail melanoma', 'necrobiosis lipoidica', 'neurofibromatosis', 'nevus spilus', 'onycholysis', 'osler node', 'paget disease breast', 'patch testing', 'pearly penile papules', 'pemphigus', 'pemphigus foliaceous', 'perleche', 'phototoxic reactions', 'pilar cyst', 'pityriasis lichenoides', 'pityriasisalbal', 'polymorphous light eruption', 'pompholyx', 'porokeratosis', 'porphyrias', 'post inflammatory hyperpigmentation', 'pretibial myxedema', 'prurigo nodularis', 'pseudomonas', 'psoriasis', 'psoriasis chronic plaque', 'psoriasis hiv', 'psoriasis pustular generalized', 'psoriasisintertrig', 'pubic lice', 'puppp', 'ridging beading', 'rosacea', 'sarcoid', 'scabies', 'scarlet fever', 'schamberg disease', 'sebaceoushyperplasia', 'sebkerm', 'seborrheic dermatitis', 'seborrheickeratosiscrop', 'sexlinkichthy', 'shoe allergy', 'skin tags polyps', 'spider bite', 'spiny keratoderma', 'stucco keratoses', 'sun damaged skin', 'sweets syndrome', 'sycosis barbae', 'syphilis', 'syringoma', 'telangiectasias', 'tinea foot webs', 'tineaankle', 'tineagroin', 'tineaincognito', 'tineaped', 'trauma', 'tricholemmoma', 'tuberous sclerosis', 'tufted folliculitis', 'urticaria vasculitis', 'varicella', 'venous lake', 'viral exanthems', 'vitiligo', 'wartcommon', 'wartperiungual', 'warts', 'warts cryotherapy', 'warts flat', 'warts immunocompromised', 'warts oral', 'warts periungual', 'warts plantar', 'xanthogranuloma', 'xanthomas', 'yellow nails']
DERMNET_SUB_DISEASE_NAME = ['AIDS', 'Axillary Granular Parakeratosis', 'Balanitis Bacterial', 'Botryomycosis Staph', 'BoxMiscIMG GP', 'Candida', 'CandidaAxillae', 'ComedonesEars', 'Coral Poisoning', 'DermatitisArm', 'DermatitisLids', 'DryFeet', 'Dyshidrosis', 'Ecthyma', 'EczemaAreolae', 'EczemaStaph', 'EpidermCystRuptured', 'Erysipelas', 'Erysipeloid', 'Fibrofolliculoma', 'Folliculitis', 'Forest', 'Furuncles Carbuncles', 'Herpes Hand', 'Hidradenitis Suppurativa Areola', 'IchthosisIMG GP', 'IchthyosisSexLinked', 'KeratosisIMG GP', 'Leprosy', 'Lichen Nitidus', 'Lichen Planus Drug', 'Lichen Planus Hypertrophic', 'Lichen Planus Oral', 'Lichen Planus Palm Soles', 'Lichen Planus Penis', 'Lichen Sclerosis Vulva', 'Lichen Sclerosus Penis', 'Lichen Sclerosus Skin', 'PUPPP', 'PerioralDerm', 'Pityriasis Lichenoides', 'PityriasisAlba', 'PostInfDesquam', 'Pseudomonas Cellulitis', 'Pseudomonas Folliculitis', 'Psoriasis Anus', 'Psoriasis Cellulitis', 'Psoriasis Guttate', 'Psoriasis Hand', 'Psoriasis Histology', 'Psoriasis Interferon Injection', 'Psoriasis inversus', 'Psoriasis nails', 'Psoriasis penis', 'Psoriasis sunburn', 'PsoriasisPinking', 'RosaceaFulFAce', 'RosaceaMilia', 'Sea bathers eruption', 'SebDermChest', 'SebDermLids', 'SebDermPresternal', 'Sebaceous glands Areola', 'SexLinkIchthosis', 'SexLinkedEchthyosis', 'Staphylococcal Folliculitis', 'SteroidPerioral', 'Streptococci Anal Penis', 'Sycosis Barbae', 'Urticaria Vasculitis', 'VascularFace', 'acanthosis nigricans', 'accessory nipple', 'accessory trachus', 'acne closed comedo', 'acne cystic', 'acne excoriated', 'acne histology', 'acne infantile', 'acne keloidalis', 'acne open comedo', 'acne primary lesion', 'acne pustular', 'acne scar', 'acquired digital fibrokeratoma', 'acrocyanosis', 'acrodermatitis enteropathica', 'actinic cheilitis sq cell lip', 'actinic comedones', 'actinic keratosis FU', 'actinic keratosis arm', 'actinic keratosis ear', 'actinic keratosis face', 'actinic keratosis hand', 'actinic keratosis horn', 'actinic keratosis lesion', 'actinic keratosis nose', 'actinic keratosis pigmented', 'actinomycosis', 'acute paronychia', 'albinism', 'allergic contact dermatitis', 'alopecia areata', 'amyloidosis', 'androgenic alopecia men', 'androgenic alopecia women', 'angioedema', 'angiokeratomas', 'angry back patch testing', 'arsenical keratoses', 'atopic', 'atypical mycobacterium', 'atypical nevi', 'atypical nevi dermoscopy', 'atypical nevi trunk', 'bacterial vaginosis', 'basal cell carcinoma', 'basal cell nevus syndrome', 'beaus lines', 'becker nevus', 'benign familial chronic pemphigus', 'biting excoriation', 'biting insects', 'black heel', 'blue nevus', 'blue nevus ota', 'bowens disease', 'bullous pemphigoid', 'cactus granuloma', 'candida groin', 'candida penis', 'candidaIntertrigo', 'candidaTongue', 'candidiasis diaper', 'candidiasis large skin folds', 'candidiasis mouth', 'candidiasis vaginal', 'cat bite', 'caterpillar dermatitis', 'cellulitis', 'chancroid', 'chapped fissured feet', 'cherry angioma', 'chilblains perniosis', 'child', 'cholinergic uriticaria', 'chondrodermatitis nodularis', 'chronic paronychia', 'clubbing', 'coccidiomycosis', 'cold urticaria', 'colloid milia', 'confluent reticulate papillomatosis', 'congenital anomalies', 'congenital nevus', 'corns', 'cosmetic fragrance allergy', 'cowden disease', 'crest syndrome', 'ctcl', 'cutaneous Larva Migrans', 'cutaneous horn', 'cylindroma', 'dariers disease', 'degos disease', 'dermagraphism', 'dermatitis herpetiformis', 'dermatitis swimming', 'dermatitisDrug', 'dermatofibroma', 'dermatofibrosarcoma', 'dermatomyositis', 'dermatosis papulosa nigra', 'desquamation', 'diabetes mellitus', 'diabetic bullae', 'discoid lupus', 'dissecting cellulitis', 'distal subungual onychomycosis', 'drug eruptions', 'duck itch', 'eczema acute', 'eczema areola', 'eczema arms', 'eczema asteatotic', 'eczema chronic', 'eczema ears', 'eczema face', 'eczema fingertips', 'eczema foot', 'eczema hand', 'eczema herpeticum', 'eczema impetiginized', 'eczema leg', 'eczema lids', 'eczema nail', 'eczema nummular', 'eczema subacute', 'eczema trunk generalized', 'eczema vulva', 'elastosis perferans', 'enterovirus', 'epidermal cyst', 'epidermal nevus', 'epidermodysplasia verruciformis', 'epidermolysis bullosa', 'erosio interdigitalis blastomycetica', 'erythema ab igne', 'erythema annulare centrifugum', 'erythema dyschromium perstans', 'erythema elevatum diutinum', 'erythema infectiosum', 'erythema multiforme', 'erythema nodosum', 'erythrasma', 'erythromelalgia', 'exfoliative dermatitis', 'exostosis', 'extramammary paget disease', 'factitial dermatitis', 'fiberglass dermatitis', 'fibroma', 'fire ants', 'fissure', 'fixed drug eruption', 'flea bites', 'folliculitis decalvans', 'fordyce spots', 'genital herpes simplex', 'genital ulcers', 'genital warts', 'gianotti crosti', 'glucagonoma', 'gonorrhea', 'granulation tissue', 'granuloma annulare', 'granuloma faciale', 'grovers disease', 'habit tic deformity', 'halo nevus', 'hand foot mouth', 'hand foot mouth disease', 'heels dry cracked', 'hemangioma', 'hemangioma infancy', 'henoch schonlein purpura', 'herpes Buttock', 'herpes buttocks', 'herpes cutaneous', 'herpes gestationis', 'herpes simplex', 'herpes type primary', 'herpes type recurrent', 'herpes zoster', 'herpesAnal', 'hidradenitis suppurativa', 'hirsutism', 'hives Urticaria Acute', 'hot comb alopecia', 'hydroa aestivale', 'hydrocystoma', 'hyperLinearCrease', 'hyperhidrosis', 'hyperkeratosis', 'ichthyosis', 'icththyosis', 'icthyosis', 'id reaction', 'idiopathic guttate hypomelanosis', 'impetigo', 'ingrown nail', 'interstitial granulomatous dermatitis', 'intertrigo', 'iododerma', 'irritant contact dermatitis', 'jelly fish sting', 'kaposi sarcoma', 'kawasaki syndrome', 'keloids', 'keratoacanthoma', 'keratolysis exfoliativa', 'keratosis punctata', 'keratosisPilaris', 'kerion', 'koilonychia', 'kyrle disease', 'leiomyomata', 'leishmaniasis', 'lentigo adults', 'lentigo maligna', 'leukemia', 'leukonychia', 'leukoplakia', 'lichen amyloidosis', 'lichen myxedematosus', 'lichen planopilaris', 'lichen planus', 'lichen planus vaginal', 'lichen simplex chronicus', 'lipoid proteinosis', 'livido reticularis', 'localized pemphigoid', 'lupus acute', 'lupus chronic cutaneous', 'lupus subacute', 'lyme disease', 'lymphangioma circumscriptum', 'maceration', 'maculae cerulea', 'majocchi granuloma', 'malignant melanoma', 'median nail dystrophy', 'melanocytic nevi', 'melanoma mimic', 'melanotic macule', 'melasma', 'meningococcemia', 'merkel cell cancer', 'metal dermatitis', 'metastasis', 'milia', 'milroy disease', 'minocycline pigmentation', 'mixed connective tissue disease', 'molluscum contagiosum', 'mongolian spot', 'morphea', 'mucinosis', 'mucous cyst', 'myiasis', 'nail distal splitting', 'nail melanoma', 'necrobiosis lipoidica', 'neurofibromas', 'neurofibromatosis', 'neurotic excoriations', 'nevoxanthoendothelioma', 'nevus anemicus', 'nevus comedonicus', 'nevus repigmented', 'nevus sebaceous', 'nevus spilus', 'normal variations', 'north american blastomycosis', 'onychogryphosis', 'onycholysis', 'otitis externa', 'pachyonychia congenita', 'paget disease breast', 'parasitosis psychogenic', 'patch testing', 'pearly penile papules', 'pediculosis body', 'pediculosis lids', 'pellagra', 'pemphigus', 'pemphigus foliaceous', 'perioral dermatitis', 'periungual fibroma', 'periungual warts', 'perleche', 'phlebitis superficial', 'phototoxic reactions', 'phototoxic reactions doxycycline', 'piebaldism', 'pigmented bands', 'pilar cyst', 'pincer nails', 'pinkus tumor', 'pitted keratolysis', 'pityriasis rosea', 'pityriasis rubra pilaris', 'pityrosporum folliculitis', 'poikiloderma civatte', 'polymorphous light eruption', 'pompholyx', 'porokeratosis', 'porphyrias', 'post inflammatory hyperpigmentation', 'pressure urticaria', 'pretibial myxedema', 'proximal subungual onychomycosis', 'prurigo nodularis', 'pseudo porphyria', 'pseudomonas', 'pseudopelade', 'pseudoxanthoma elasticum', 'psoriasis', 'psoriasis Chronic plaque', 'psoriasis digits', 'psoriasis erythrodermic', 'psoriasis palms soles', 'psoriasis pustular generalized', 'psoriasis scalp', 'pubic lice', 'purpura vomiting', 'pyoderma gangrenosum', 'pyogenic granuloma', 'raynaud disease', 'reiter syndrome', 'rheumatoid nodule', 'rhinophyma', 'rhus dermatitis', 'ridging beading', 'rocky mountain spotted fever', 'rosacea', 'rosacea nose', 'rosacea steroid', 'roseola infantum', 'sarcoid', 'scabies', 'scarlet fever', 'schamberg disease', 'scleroderma', 'sebDerem', 'sebKerm', 'sebaceous adenoma', 'sebaceous glands upper lip', 'sebaceous hyperplasia', 'seborrheic dermatitis', 'seborrheic keratoses ruff', 'seborrheic keratoses smooth', 'seborrheic keratosis irritated', 'shoe allergy', 'skin tags polyps', 'small pox', 'spider angioma', 'spider bite', 'splinter hemorrhage', 'squamous cell carcinoma ear', 'squamous cell carcinoma face', 'squamous cell carcinoma hand arm', 'squamous cell carcinoma leg', 'squamous cell carcinoma lesion', 'squamous cell carcinoma lip', 'squamous cell carcinoma nose', 'squamous cell carcinoma scalp', 'squamous cell carcinoma vulva', 'stasis dermatitis', 'stevens johnson syndrome', 'stucco keratoses', 'subungual hematoma', 'sun damaged skin', 'sweets syndrome', 'syphilis', 'syringoma', 'systemically induced allergic dermatitis', 'telangiectasias', 'telogen effluvium', 'terry nails', 'thrombosed vein', 'tick bite', 'tinea beard', 'tinea body', 'tinea face', 'tinea foot dorsum', 'tinea foot plantar', 'tinea foot webs', 'tinea groin', 'tinea hand dorsum', 'tinea incognito', 'tinea laboratory', 'tinea palm', 'tinea primary lesion', 'tinea scalp', 'tinea versicolor', 'tineaAmiantacea', 'trauma', 'trichofolliculoma', 'trichorrhexis nodosa', 'trichotillomania', 'tuberous sclerosis', 'tufted folliculitis', 'twenty nail dystrophy', 'unilateral telangiectasia', 'varicella', 'vascular anomaly', 'vasculitis', 'venous lake', 'venous malformations', 'verrucous carcinoma', 'viral exanthems', 'vitiligo', 'warts common', 'warts cryotherapy', 'warts digitate', 'warts flat', 'warts genital', 'warts immunocompromised', 'warts mouth', 'warts oral', 'warts periungual', 'warts plantar', 'warts treatment', 'weathering nodules', 'white superficial onychomycosis', 'xanthomas', 'xlinkedIcthyosis', 'yellow nails']
PAD_DISEASE_NAME = ['Actinic Keratosis', 'Basal Cell Carcinoma', 'Melanoma', 'Nevus', 'Seborrheic Keratosis', 'Squamous Cell Carcinoma']
DDI_DISEASE_NAME = ['abrasions-ulcerations-and-physical-injuries', 'acrochordon', 'actinic-keratosis', 'angioma', 'arteriovenous-hemangioma', 'basal-cell-carcinoma', 'benign-keratosis', 'blue-nevus', 'dermatofibroma', 'dysplastic-nevus', 'eccrine-poroma', 'eczema-spongiotic-dermatitis', 'epidermal-cyst', 'hyperpigmentation', 'inverted-follicular-keratosis', 'kaposi-sarcoma', 'lipoma', 'melanocytic-nevi', 'melanoma', 'metastatic-carcinoma', 'molluscum-contagiosum', 'mycosis-fungoides', 'neurofibroma', 'nevus-lipomatosus-superficialis', 'prurigo-nodularis', 'pyogenic-granuloma', 'seborrheic-keratosis', 'solar-lentigo', 'squamous-cell-carcinoma', 'trichilemmoma', 'verruca-vulgaris']
BINARY_DISEASE_NAME = ['Benign', 'Malignant']
BCN_DISEASE_NAME = ['Basal cell carcinoma', 'Dermatofibroma', 'Melanoma NOS', 'Melanoma metastasis', 'Nevus', 'Scar', 'Seborrheic keratosis', 'Solar lentigo', 'Solar or actinic keratosis', 'Squamous cell carcinoma NOS']