DERMNET_DISEASE_NAME = ['Acne and Rosacea Photos',
                        'Actinic Keratosis Basal Cell Carcinoma and other Malignant Lesions',
                        'Atopic Dermatitis Photos',
                        'Bullous Disease Photos',
                        'Cellulitis Impetigo and other Bacterial Infections',
                        'Eczema Photos',
                        'Exanthems and Drug Eruptions',
                        'Hair Loss Photos Alopecia and other Hair Diseases',
                        'Herpes HPV and other STDs Photos',
                        'Light Diseases and Disorders of Pigmentation',
                        'Lupus and other Connective Tissue diseases',
                        'Melanoma Skin Cancer Nevi and Moles',
                        'Nail Fungus and other Nail Disease',
                        'Poison Ivy Photos and other Contact Dermatitis',
                        'Psoriasis pictures Lichen Planus and related diseases',
                        'Scabies Lyme Disease and other Infestations and Bites',
                        'Seborrheic Keratoses and other Benign Tumors',
                        'Systemic Disease',
                        'Tinea Ringworm Candidiasis and other Fungal Infections',
                        'Urticaria Hives',
                        'Vascular Tumors',
                        'Vasculitis Photos',
                        'Warts Molluscum and other Viral Infections']
SYNONYM_DICT_HAM10000 = {
    'acne and rosacea photos': {'rosacea acne', 'sebDerem', 'rosacea steroid', 'Forest', 'acne pustular',
                                'hidradenitis suppurativa', 'fordyce spots', 'acne scar', 'Sebaceous glands Areola',
                                'SteroidPerioral', 'RosaceaFulFAce', 'nevus comedonicus', 'Perioral Derm Eye',
                                'RosaceaOK', 'rosacea', 'VascularFace', 'rhnophymas', 'hyperhidrosis', 'acne',
                                'Rhinophyma', 'rhinophyma', 'ComedonesEars', 'acne histology', 'rosacea nose',
                                'Hidradenitis Suppurativa Areola', 'PerioralDerm', 'acne rosacea', 'RosaceaMilia',
                                'acne closed comedo', 'sebaceous glands upper lip', 'milia', 'acne primary lesion',
                                'perioral dermatitis', 'acne cystic', 'acne open comedo', 'acne infantile',
                                'acne excoriated', 'minocycline pigmentation'},
    'actinic keratosis basal cell carcinoma and other malignant lesions': {'squamous cell carcinoma hand arm',
                                                                           'extramammary paget disease', 'leukoplakia',
                                                                           'actinic cheilitis sq cell lip',
                                                                           'basal cell carcinoma nose',
                                                                           'actinic keratosis arm',
                                                                           'epidermodysplasia verruciformis',
                                                                           'merkel cell cancer', 'dermatofibrosarcoma',
                                                                           'actinic keratosis lesion',
                                                                           'basal cell carcinoma superficial',
                                                                           'basal cell carcinoma ear',
                                                                           'squamous cell carcinoma ear',
                                                                           'basal cell carcinoma sclerosing',
                                                                           'arsenical keratoses',
                                                                           'basal cell carcinoma trunk ext', 'ak',
                                                                           'squamous cell carcinoma nose',
                                                                           'actinic keratosis nose', 'keratosis',
                                                                           'squamous cell carcinoma scalp',
                                                                           'basal cell carcinoma lesion',
                                                                           'actinic keratosis',
                                                                           'actinic keratosis horn',
                                                                           'granulation tissue', 'bowens disease',
                                                                           'actinic keratosis pigmented',
                                                                           'squamous cell carcinoma lesion',
                                                                           'actinic keratosis face',
                                                                           'actinic keratosis hand', 'ctcl',
                                                                           'malignant lesion', 'leukemia',
                                                                           'basal cell nevus syndrome',
                                                                           'paget disease breast',
                                                                           'actinic keratosis ear', "bowen's",
                                                                           'verrucous carcinoma',
                                                                           'basal cell carcinoma aldara',
                                                                           'squamous cell carcinoma vulva', 'bowen',
                                                                           'squamous cell carcinoma leg',
                                                                           'cutaneous horn',
                                                                           'squamous cell carcinoma lip',
                                                                           'basal cell carcinoma lid',
                                                                           'basal cell carcinoma pigmented',
                                                                           'metastasis', 'basal cell carcinoma lip',
                                                                           'basal cell carcinoma histology',
                                                                           'squamous cell carcinoma face',
                                                                           'basal cell carcinoma face', 'actinic',
                                                                           'basal cell carcinoma scalp',
                                                                           'basal cell carcinoma', 'bcc',
                                                                           'actinic keratosis FU',
                                                                           'basal cell carcinoma arm'},
    'atopic dermatitis photos': {'IMG', 'PityriasisAlba', 'atopicChild', 'EczemaAreolae', 'KeratosisIMG GP',
                                 'DermatitisAreola', 'diaperDerm', 'hyperLinearCrease', 'Ichthyosis', 'Atopic',
                                 'IchthyosisSexLinked', 'KeratosisPilaris', 'hyperkeratosis', 'atopicDermok',
                                 'DermatitisLids', 'kerPilarisFlorid', 'keratosisPilaris', 'icthyosis',
                                 'IchthosisIMG GP', 'AtopicFacek', 'SexLinkedEchthyosis', 'ichthyosis', 'atopicFoot',
                                 '.DS Store', 'atopicAdult', 'child', 'atopicFeet', 'atopic dermatitis', 'atopic',
                                 'icththyosis', 'AtopicMouth', 'AtopicLichenification', 'atopicFace', 'DryFeet',
                                 'AtopicFossaq', 'AtopicChild', 'AtopicIMG GP', 'atopicFlid', 'AtopicFaceok',
                                 'AtopicFace', 'xlinkedIcthyosis', 'thIMG', 'AtopicDerm', 'eczema', 'SexLinkIchthosis'},
    'bullous disease photos': {'localized pemphigoid', 'bullous pemphigoid', 'chronic bullous dermatosis childhood',
                               'dermatitis herpetiformis', 'dariers disease', 'pemphigus foliaceous', 'pemphigus',
                               'diabetic bullae', 'bullous disease', 'pemphigoid', 'herpes gestationis',
                               'grovers disease', 'benign familial chronic pemphigus', 'epidermolysis bullosa'},
    'cellulitis impetigo and other bacterial infections': {'bacterial infection', 'Erysipelas',
                                                           'Streptococci Anal Penis', 'Cellulitis', 'Sycosis Barbae',
                                                           'pitted keratolysis', 'HotTubIMG GP',
                                                           'Staphylococcal Folliculitis', 'Furuncles Carbuncles',
                                                           'Balanitis Bacterial', 'Pseudomonfoll', 'Erysipeloid',
                                                           'otitis externa', 'atypical mycobacterium', 'Leprosy',
                                                           'Pseudomonas Folliculitis', 'meningococcemia', 'EczemaStaph',
                                                           'Ecthyma', 'Folliculitis', 'Botryomycosis Staph', 'impetigo',
                                                           'cellulitis', 'Pseudomonas Cellulitis'},
    'eczema photos': {'stasis dermatitis', 'DermatitisLeg', 'eczema axillae', 'eczema chronic', 'eczema hand',
                      'maceration', 'eczema subacute', 'DermatitisArm', 'eczema trunk generalized', 'eczema face',
                      'milroy disease', 'hyperkeratosis', 'DermatitisLids', 'eczema arms', 'eczema ears',
                      'desquamation', 'fissure', 'dermatitisDrug', 'dermatitis', 'eczema lids', 'pompholyx',
                      'parasitosis psychogenic', 'eczema impetiginized', 'eczema nummular', 'factitial dermatitis',
                      'eczema vulva', 'heels dry cracked', 'fiberglass dermatitis', 'phlebitis superficial',
                      'chapped fissured feet', 'eczema areola', 'eczema leg', 'Dyshidrosis', 'lichen simplex chronicus',
                      'eczema fingertips', 'keratolysis exfoliativa', 'eczema foot', 'eczema asteatotic',
                      'neurotic excoriations', 'eczema', 'prurigo nodularis', 'iododerma', 'eczema acute',
                      'id reaction'},
    'exanthems and drug eruptions': {'drug eruptions', 'gianotti crosti', 'viral exanthems', 'hand foot mouth disease',
                                     'cytomegalovirus', 'scarlet fever', 'PostInfDesquam', 'kawasaki syndrome',
                                     'exfoliative dermatitis', 'desquamationViral GP', 'drug reaction', 'exanthem',
                                     'fixed drug eruption', 'roseola infantum', 'enterovirus',
                                     'minocycline pigmentation', 'drug eruption', 'erythema infectiosum'},
    'hair loss photos alopecia and other hair diseases': {'hirsutism', 'alopecia', 'acne keloidalis',
                                                          'trichorrhexis nodosa', 'pseudopelade',
                                                          'androgenic alopecia women', 'trichotillomania',
                                                          'androgenic alopecia men', 'alopecia areata',
                                                          'telogen effluvium', 'pili torti', 'dissecting cellulitis',
                                                          'baldness', 'discoid lupus', 'tufted folliculitis',
                                                          'hair loss', 'lichen planopilaris', 'hot comb alopecia',
                                                          'folliculitis decalvans'},
    'herpes hpv and other stds photos': {'AIDS', 'warts mouth', 'herpes type  primary', 'herpesAnal', 'warts genital',
                                         'herpes type  recurrent', 'std', 'bacterial vaginosis', 'chancroid',
                                         'sexually transmitted disease', 'herpes', 'gonorrhea', 'pearly penile papules',
                                         'molluscum contagiosum', 'syphilis', 'genital herpes simplex', 'genital warts',
                                         'hpv', 'genital ulcers'},
    'light diseases and disorders of pigmentation': {'hydroa aestivale', 'nevus anemicus',
                                                     'erythema dyschromium perstans', 'colloid milia',
                                                     'phototoxic reactions doxycycline', 'sun damaged skin',
                                                     'light disease', 'erythema ab igne', 'pigmentation disorder',
                                                     'vitiligo', 'albinism', 'mongolian spot', 'melasma',
                                                     'polymorphous light eruption', 'weathering nodules',
                                                     'actinic comedones', 'idiopathic guttate hypomelanosis', 'milia',
                                                     'post inflammatory hyperpigmentation', 'poikiloderma civatte',
                                                     'phototoxic reactions', 'lentigo adults', 'porphyrias',
                                                     'pseudo porphyria', 'piebaldism'},
    'lupus and other connective tissue diseases': {'lupus subacute', 'scleroderma', 'lupus acute',
                                                   'mixed connective tissue disease', 'systemic lupus erythematosus',
                                                   'erythromelalgia', 'dermatomyositis', 'lupus chronic cutaneous',
                                                   'mucinosis', 'sle', 'connective tissue disease', 'acrocyanosis',
                                                   'crest syndrome', 'raynaud disease', 'lupus', 'rheumatoid nodule',
                                                   'chilblains perniosis', 'morphea'},
    'melanoma skin cancer nevi and moles': {'halo nevus', 'nevus repigmented', 'blue nevus', 'nevus',
                                            'melanotic macule', 'nevus spilus', 'melanocytic nevus', 'blue nevus ota',
                                            'congenital nevus', 'atypical nevi dermoscopy', 'melanocytic nevi',
                                            'malignant melanoma', 'lentigo maligna', 'skin cancer', 'melanoma',
                                            'becker nevus', 'atypical nevi', 'atypical nevi trunk', 'mole',
                                            'mongolian spot'},
    'nail fungus and other nail disease': {'psoriasis', 'ingrown nail', 'koilonychia', 'acute paronychia',
                                           'congenital anomalies', 'splinter hemorrhage', 'yellow nails', 'onycholysis',
                                           'onychogryphosis', 'nail fungus', 'nail melanoma', 'normal variations',
                                           'mucous cyst', 'biting excoriation', 'ridging beading', 'trauma',
                                           'beaus lines', 'exostosis', 'fissure', 'proximal subungual onychomycosis',
                                           'onychomycosis', 'nail distal splitting', 'pincer nails',
                                           'chronic paronychia', 'alopecia areata', 'habit tic deformity',
                                           'periungual fibroma', 'pigmented bands', 'Bed Ridges',
                                           'pachyonychia congenita', 'white superficial onychomycosis', 'leukonychia',
                                           'lichen planus', 'BedRidges', 'periungual warts', 'terry nails', 'clubbing',
                                           'twenty nail dystrophy', 'distal subungual onychomycosis', 'eczema nail',
                                           'pseudomonas', 'median nail dystrophy', 'nail disease',
                                           'subungual hematoma'},
    'poison ivy photos and other contact dermatitis': {'allergic contact dermatitis', 'rhus dermatitis',
                                                       'cosmetic fragrance allergy', 'contact dermatitis',
                                                       'patch testing', 'metal dermatitis', 'poison ivy',
                                                       'angry back patch testing', 'allergic reaction', 'shoe allergy',
                                                       'systemically induced allergic dermatitis',
                                                       'irritant contact dermatitis'},
    'psoriasis pictures lichen planus and related diseases': {'psoriasisAnus', 'psoriasis', 'sebKerm',
                                                              'psoriasis digits', 'psoriasis palms soles',
                                                              'SebDermChest', 'Pityriasis Lichenoides',
                                                              'psoriatic arthritis', 'reiter syndrome',
                                                              'Lichen Sclerosis Vulva', 'SebDermPresternal',
                                                              'Psoriasis inversus', 'SebDermLids',
                                                              'Lichen Sclerosus Skin', 'Lichen Planus Hypertrophic',
                                                              'Psoriasis', 'sebdermFace', 'PsoriasisAnalPink',
                                                              'Lichen Nitidus', 'PsoriasisPinking', 'SebDermPrestern',
                                                              'Psoriasis sunburn', 'Lichen Sclerosus Penis',
                                                              'glutealPinking', 'lichen planus vaginal',
                                                              'Lichen Planus Drug', 'Lichen Planus Palm Soles',
                                                              'Psoriasis nails', 'Psoriasis Cellulitis',
                                                              'Lichen Planus Penis', 'psoriasis scalp',
                                                              'seborrheic dermatitis', 'Lichen Planus Oral',
                                                              'Psoriasis Hand', 'Axillary Granular Parakeratosis',
                                                              'pityriasis rosea', 'psoriasis erythrodermic',
                                                              'Psoriasis Chronic Plaque', 'Psoriasis Anus',
                                                              'psoriasis Chronic plaque', 'Psoriasis penis',
                                                              'Psoriasis Interferon Injection', 'lichen planus',
                                                              'psoriasis pustular generalized', 'OilSpotPsoriasis',
                                                              'tineaAmiantacea', 'pityriasis rubra pilaris',
                                                              'Psoriasis Guttate', 'Psoriasis Histology'},
    'scabies lyme disease and other infestations and bites': {'biting insects', 'rocky mountain spotted fever',
                                                              'cutaneous Larva Migrans', 'pubic lice',
                                                              'Coral Poisoning', 'caterpillar dermatitis',
                                                              'leishmaniasis', 'lyme disease', 'tick bite', 'duck itch',
                                                              'pediculosis body', 'dermatitis swimming',
                                                              'cactus granuloma', 'maculae cerulea',
                                                              'chigger Bites Bullous', 'BoxMiscIMG GP',
                                                              'Sea bathers eruption', 'scabies', 'jelly fish sting',
                                                              'cat bite', 'infestation', 'spider bite', 'myiasis',
                                                              'pediculosis lids', 'fire ants', 'flea bites'},
    'seborrheic keratoses and other benign tumors': {'seborrheic keratosis', 'hydrocystoma', 'accessory trachus',
                                                     'epidermal cyst', 'accessory nipple', 'follicular keratosis',
                                                     'dermatofibroma', 'syringoma', 'fibroma', 'collagenoma',
                                                     'seborrheic keratoses ruff', 'keratosis punctata',
                                                     'pseudo cyst auricle', 'dermatosis papulosa nigra',
                                                     'kyrle disease', 'chondrodermatitis nodularis', 'benign tumor',
                                                     'seborrheic keratoses smooth', 'acquired digital fibrokeratoma',
                                                     'pinkus tumor', 'neurofibromas', 'sebaceous hyperplasia',
                                                     'epidermal nevus', 'EpidermCystRuptured', 'skin tags polyps',
                                                     'stucco keratoses', 'melanoma mimic', 'cylindroma', 'skin tag',
                                                     'porokeratosis', 'trichofolliculoma', 'pilar cyst', 'keloids',
                                                     'seborrheicKeratosisCrop', 'Keratoacanthoma', 'keratoacanthoma',
                                                     'leiomyomata', 'seborrheic keratosis irritated',
                                                     'nevus sebaceous'},
    'systemic disease': {'necrobiosis lipoidica', 'lichen myxedematosus', 'amyloidosis', 'systemic disease', 'pellagra',
                         'pseudoxanthoma elasticum', 'granuloma annulare', 'degos disease', 'lipoid proteinosis',
                         'glucagonoma', 'sarcoid', 'rheumatoid nodule', 'pretibial myxedema', 'myxedema',
                         'internal disease', 'sebaceous adenoma', 'xanthomas', 'acanthosis nigricans',
                         'acrodermatitis enteropathica', 'elastosis perferans', 'nevoxanthoendothelioma',
                         'neurofibromatosis', 'tuberous sclerosis', 'Fibrofolliculoma', 'osler node',
                         'diabetes mellitus', 'lichen amyloidosis', 'cowden disease'},
    'tinea ringworm candidiasis and other fungal infections': {'kerion', 'actinomycosis', 'candidiasis vaginal',
                                                               'tinea', 'pitted keratolysis', 'candida groin',
                                                               'candida penis', 'confluent reticulate papillomatosis',
                                                               'candidaTongue', 'tinea hand dorsum', 'perleche',
                                                               'tinea body', 'tinea versicolor', 'tinea laboratory',
                                                               'tinea scalp', 'tinea incognito', 'TineaIncognito',
                                                               'tinea face', 'tinea beard', 'tinea groin',
                                                               'tinea primary lesion', 'tinea palm', 'CandidaAxillae',
                                                               'candidaIntertrigo', 'erythrasma', 'majocchi granuloma',
                                                               'north american blastomycosis', 'candidiasis Penis',
                                                               'candidiasis', 'candidiasis mouth', 'Candida',
                                                               'cheilitis', 'pityrosporum folliculitis',
                                                               'candidiasis diaper', 'ringworm', 'fungal infection',
                                                               'coccidiomycosis', 'tinea foot webs',
                                                               'tinea foot plantar', 'candidiasis large skin folds',
                                                               'tinea foot dorsum', 'intertrigo', 'id reaction',
                                                               'erosio interdigitalis blastomycetica'},
    'urticaria hives': {'dermagraphism', 'angioedema', 'hives Urticaria Acute', 'urticaria', 'Urticaria Vasculitis',
                        'cholinergic uriticaria', 'cold urticaria', 'PUPPP', 'hives', 'erythema annulare centrifugum',
                        'wheal', 'pressure urticaria'},
    'vascular tumors': {'thrombosed vein', 'cherry angioma', 'angioma', 'hemangioma infancy', 'Hemangioma Dermoscopy',
                        'angiokeratomas', 'venous lake', 'lymphangioma circumscriptum', 'vascular anomaly',
                        'unilateral telangiectasia', 'pyogenic granuloma', 'hemangioma', 'kaposi sarcoma',
                        'telangiectasias', 'vascular tumor', 'venous malformations', 'purpura vomiting',
                        'spider angioma'},
    'vasculitis photos': {'vasculitis', 'schamberg disease', 'pyoderma gangrenosum', 'livido reticularis',
                          'sweets syndrome', 'atrophy blanche', 'blood vessel', 'stevens johnson syndrome',
                          'granuloma faciale', 'erythema elevatum diutinum', 'henoch schonlein purpura',
                          'erythema multiforme', 'interstitial granulomatous dermatitis', 'erythema nodosum',
                          'inflammation'},
    'warts molluscum and other viral infections': {'warts plantar', 'herpes type  recurrent', 'ChickenPoxBack',
                                                   'herpes zoster', 'small pox', 'hand foot mouth', 'black heel',
                                                   'eczema herpeticum', 'molluscum contagiosum', 'warts oral',
                                                   'warts periungual', 'warts immunocompromised', 'herpes simplex',
                                                   'herpes Buttock', 'herpes type  primary', 'Herpes Hand',
                                                   'warts treatment', 'herpes mouth', 'warts flat', 'PeriungualWart',
                                                   'warts', 'herpes buttocks', 'herpes cutaneous', 'viral infection',
                                                   'warts cryotherapy', 'varicella', 'molluscum', 'wartmouth',
                                                   'wartMouth', 'warts common', 'eczema vaccinatum', 'wartCommon',
                                                   'corns', 'warts digitate'}}

ISIC_DISEASE_NAME = [
    'Malignant',
    'Benign'
]
ISIC_PRECSV_PATH = './PanDerm_ISIC_predprob.csv'

MEDGAMMA_EVALUATION_PATH = '/Volumes/T7/SkinGPT-X-EvaluationResults/Experiments/Diagnosis/Medgamma/filename_to_medgamma_pred.csv'
REASONINGLAYER_EVALUATION_PATH = '/Volumes/T7/SkinGPT-X-EvaluationResults/Experiments/Diagnosis/DermNet/SkinGPTX/Reasoning_output.csv'
CASEREVIEW_EVALUATION_PATH = '/Volumes/T7/SkinGPT-X-EvaluationResults/Experiments/Diagnosis/DermNet/SkinGPTX/CaseReview_output.csv'
MEDGAMMA_LABELS_PATH = '/Volumes/T7/SkinGPT-X-EvaluationResults/Experiments/Diagnosis/filename_to_label.csv'
REASONING_LABELS_PATH = '/Volumes/T7/SkinGPT-X-EvaluationResults/Experiments/Diagnosis/DermNet/SkinGPTX/filename_to_labels_Reasoning.csv'
CASEREVIEW_LABELS_PATH = '/Volumes/T7/SkinGPT-X-EvaluationResults/Experiments/Diagnosis/DermNet/SkinGPTX/filename_to_labels_CaseReview.csv'
BASE_IMAGE_DIRECTORY = '/Volumes/T7/SkinGPT-X-Dataset/Dermnet/test'

MEDGAMMA_WORDHIT_OUTPUT = '/Volumes/T7/SkinGPT-X-EvaluationResults/Experiments/Diagnosis/SkinGPTX/MEDGAMMA_word_hit.csv'
CASEREVIEW_WORDHIT_OUTPUT = '/Volumes/T7/SkinGPT-X-EvaluationResults/Experiments/Diagnosis/DermNet/SkinGPTX/CaseReview_word_hit.csv'
REASONING_WORDHIT_OUTPUT = '/Volumes/T7/SkinGPT-X-EvaluationResults/Experiments/Diagnosis/DermNet/SkinGPTX/REASONING_word_hit.csv'

DERMNET_DATASET_ROOT = '/Volumes/T7/SkinGPT-X-Dataset/Dermnet/test'
ISIC_DATASET_ROOT = '/Volumes/T7/SkinGPT-X-Dataset/ISIC_2024_Resize224/test'
ISIC_EVALUATION_ROOT = '/Volumes/T7/SkinGPT-X-EvaluationResults/ISIC/test'

DERMNET_EVALUATION_ROOT = '/Volumes/T7/SkinGPT-X-EvaluationResults/Dermnet/test'

SYNONYM_DICT = {
    "vascular": {"vasculitis", "vascular", "vasculitic"},
    "carcinoma": {"carcinoma"},
    "acne": {"acne", "acneiform", "actinic cheilitis"},
    "rosacea": {"rosacea", "rosaceous"},
    "candidiasis": {"candidiasis", "candidal"},
    "icththyosis": {"ichthyosis", "icththyosis"},
    "icthyosis": {"icthyosis", "ichthyosis", "icththyosis"},
    "kerpilarisflorid": {"keratosis", "kerpilarisflorid"},
    "dermatitis": {"dermatitis", "dermatomyositis", "dermatosis"},
    "pemphigoid": {"pemphigoid", "pemphigus"},
    "palm": {"palms", "palm"},
    "urticaria": {"urticaria", "urticarial"},
    "lesions": {"lesions", "lesion"},
    "heels": {"heels", "heel"},
    "eruptions": {"eruptions", "eruption"},
    "infections": {"infection", "infections"},
    "comedo": {"comedones"},
    "actinic": {"ak", "actinic"},
    "tumors": {"angiokeratomas", "tumors", "angiosarcoma", "angioma", "angiomas", "angiokeratoma", "melanoma"},
    "steroidperioral": {"steroidperioral", "perioral"},
    "exanthems": {"exanthems", "exabrgens", "rubra", "cutaneous", "larva", "migrans", "multiforme", "erythematosus",
                  "exanthem", "zoster", "miliaria", "infectiosum", "syphilis"},
    "eczema": {"eczematous", "eczema"}
}
